name: Build container image
on:
  workflow_dispatch:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout files in repo
      uses: actions/checkout@main
    - name: update jupyter dependencies with repo2docker
      uses: jupyterhub/repo2docker-action@master
      with: 
        DOCKER_USERNAME: ${{github.actor}}
        DOCKER_PASSWORD: ${{secrets.GITHUB_TOKEN}}
        DOCKER_REGISTRY: "ghcr.io"
        APPENDIX_FILE: .binder/appendix
