name: Build container image
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/build-container-image.yml
      - container/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3
      - name: Checkout configurations
        uses: actions/checkout@v5
        with:
          sparse-checkout: container
      - name: Move configurations
        run: |
          mv container/* .
          rmdir container
      - name: Run repo2docker
        uses: itcarroll/repo2docker-action@registry-cache
        with:
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_REGISTRY: "ghcr.io"
          APPENDIX_FILE: appendix
          REPO_DIR: /tmp
